name: Vercel Deployment

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest

        name: Publish to Vercel
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Deploy to Vercel Action
              uses: BetaHuhn/deploy-to-vercel-action@latest
              with:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_DEPLOY }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
