name: Vercel Deployment

on:
    push:
        branches: [main]
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

        branches: [main]

env:
    CI: false

jobs:
    publish:
        runs-on: ubuntu-latest

        name: Publish to Vercel
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Generate Env File
              run: |
                  echo "REACT_APP_KAKAO_CLIENT_ID=$REACT_APP_KAKAO_CLIENT_ID" >> .env
                  echo "REACT_APP_HUGGINGFACE_API_KEY=$REACT_APP_HUGGINGFACE_API_KEY" >> .env
                  echo "REACT_APP_HUGGINGFACE_API_URL=$REACT_APP_HUGGINGFACE_API_URL" >> .env
                  echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env
              env:
                  REACT_APP_KAKAO_CLIENT_ID: ${{secrets.REACT_APP_KAKAO_CLIENT_ID}}
                  REACT_APP_HUGGINGFACE_API_KEY: ${{secrets.REACT_APP_HUGGINGFACE_API_KEY}}
                  REACT_APP_HUGGINGFACE_API_URL: ${{secrets.REACT_APP_HUGGINGFACE_API_URL}}
                  REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build

            - name: Deploy to Vercel Action
              uses: BetaHuhn/deploy-to-vercel-action@latest
              with:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_DEPLOY }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
